---
- hosts: vag_box
  vars_files:
    - config_vag_box.yml  
  tasks:
    - name: Include nodejs Role
      include_role:
        name: nodejs
    - name: Include nginx Role
      include_role:
        name: nginx

- hosts: other_box
  vars_files:
    - config_other_box.yml  
  tasks:
    - name: Include nodejs Role
      include_role:
        name: nodejs
  
