- name: Install Nginx.
  yum: name="nginx" state=present
  become: yes

- name: Change the default config file with dummyDefault.conf.
  copy:
    src: "./dummyDefault.conf"  
    dest: "/etc/nginx/conf.d/default.conf"
  become: yes

- name: Start Nginx.
  service: 
    name: nginx
    state: restarted
    enabled: yes  
  become: yes